name: refresh

on:
  schedule:
    # 北京时间 10:53
    - cron: '53 2 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  access-url:
    runs-on: ubuntu-latest
    steps:
      - name: purge jsdelivr cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/882019/66882019/666.txt"
          echo "Purge request sent"
